version: "3"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bortexel
      MYSQL_DATABASE: buildings
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
  server:
    image: localhost:5000/bortexel/buildings:latest
    depends_on:
      - mysql
    restart: always
    ports:
      - "7878:8080"
    environment:
      BB_SQL_HOST: mysql
      BB_SQL_USER: root
      BB_SQL_PASSWORD: bortexel
      BB_SQL_DATABASE: buildings
    volumes:
      - /etc/bortexel/buildings:/home/container/data
volumes:
  mysql-data: