name: Build Go and Docker image

on:
  push:
    branches: [ master ]

jobs:
  build-go:
    name: Build Go Binary
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies and build
        run: |
          go get -d ./... &&
          go build -o buildings
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build-artifacts
          path: buildings
  build-docker:
    needs: build-go
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out to the root
        uses: actions/checkout@v2
      - name: Download latest binary
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Build, tag, and push Docker image to registry
        run: |
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }} registry.ruscalworld.ru
          docker build -t registry.ruscalworld.ru/bortexel/buildings:latest .
          docker push registry.ruscalworld.ru/bortexel/buildings:latest